name: StoneArtifacts
api-version: 1.20
version: 1.0
main: me.truewin.StoneArtifacts.Main

commands:
  sadrop:
    permission: StoneArtifacts.sadrop
  sagive:
    permission: StoneArtifacts.sagive